//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleWorkShop
    {
        public BibleWorkShop()
        {
            this.RegistrationMasters = new HashSet<RegistrationMaster>();
        }
    
        public int BWSID { get; set; }
        public string BWSCode { get; set; }
        public string Place { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> WorkShopNo { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<RegistrationMaster> RegistrationMasters { get; set; }
    }
}
