//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksRequest
    {
        public int BRId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<bool> IsStatus { get; set; }
        public Nullable<System.DateTime> Requestdate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
    
        public virtual LibraryIndex LibraryIndex { get; set; }
        public virtual User User { get; set; }
    }
}
