//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChaptersInfo
    {
        public ChaptersInfo()
        {
            this.Dailyverses = new HashSet<Dailyvers>();
        }
    
        public int ChapterId { get; set; }
        public string ChapterNameTamil { get; set; }
        public string ChapterNameEnglish { get; set; }
        public Nullable<int> LastChapter { get; set; }
    
        public virtual ICollection<Dailyvers> Dailyverses { get; set; }
    }
}
