//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dailyvers
    {
        public int VersesId { get; set; }
        public string Title { get; set; }
        public string VersesContent { get; set; }
        public string VersesExplanation { get; set; }
        public int ChapterId { get; set; }
        public Nullable<int> ChapterNo { get; set; }
        public Nullable<int> VersesFrom { get; set; }
        public Nullable<int> VersesTo { get; set; }
        public Nullable<System.DateTime> ShowingDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual ChaptersInfo ChaptersInfo { get; set; }
    }
}
