//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents_Test
    {
        public int IntId { get; set; }
        public string DocumentID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> DownloadCount { get; set; }
        public string DocumentReference { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ImagesPath { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
