//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBooksDownloadDetail
    {
        public int DownloadId { get; set; }
        public Nullable<int> BooKId { get; set; }
        public string DownloadedBy { get; set; }
        public Nullable<System.DateTime> DownloadedDateTime { get; set; }
        public string DownloadeIP { get; set; }
        public string DownloadedLocation { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DownloadCount { get; set; }
    
        public virtual EBooksIndex EBooksIndex { get; set; }
    }
}
