//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElshaddaiDBContext : DbContext
    {
        public ElshaddaiDBContext()
            : base("name=ElshaddaiDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BibleCommentary> BibleCommentaries { get; set; }
        public DbSet<BibleCommentaryDownloadDetail> BibleCommentaryDownloadDetails { get; set; }
        public DbSet<BibleDictionary> BibleDictionaries { get; set; }
        public DbSet<BibleDictionaryDownloadDetail> BibleDictionaryDownloadDetails { get; set; }
        public DbSet<BibleWorkShop> BibleWorkShops { get; set; }
        public DbSet<BiblicalTheology> BiblicalTheologies { get; set; }
        public DbSet<BiblicalTheologyDownloadDetail> BiblicalTheologyDownloadDetails { get; set; }
        public DbSet<BookRequest> BookRequests { get; set; }
        public DbSet<BooksRequest> BooksRequests { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ChaptersInfo> ChaptersInfoes { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<CommentsAndSuggestion> CommentsAndSuggestions { get; set; }
        public DbSet<Dailyvers> Dailyverses { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DownloadDetail> DownloadDetails { get; set; }
        public DbSet<EBooksDownloadDetail> EBooksDownloadDetails { get; set; }
        public DbSet<EBooksIndex> EBooksIndexes { get; set; }
        public DbSet<EmailMessage> EmailMessages { get; set; }
        public DbSet<LibraryIndex> LibraryIndexes { get; set; }
        public DbSet<LibrayBook> LibrayBooks { get; set; }
        public DbSet<LibrayDownloadDetail> LibrayDownloadDetails { get; set; }
        public DbSet<LogError> LogErrors { get; set; }
        public DbSet<LoggedInDetail> LoggedInDetails { get; set; }
        public DbSet<MarianBook> MarianBooks { get; set; }
        public DbSet<MarianBookDownloadDetail> MarianBookDownloadDetails { get; set; }
        public DbSet<MarianStudy> MarianStudies { get; set; }
        public DbSet<MarianStudyDownloadDetail> MarianStudyDownloadDetails { get; set; }
        public DbSet<PrayerNote> PrayerNotes { get; set; }
        public DbSet<PrayerNoteDownloadDetail> PrayerNoteDownloadDetails { get; set; }
        public DbSet<PrayerRain> PrayerRains { get; set; }
        public DbSet<PrayerRainDownloadDetail> PrayerRainDownloadDetails { get; set; }
        public DbSet<RegistrationMaster> RegistrationMasters { get; set; }
        public DbSet<SinaiLetter> SinaiLetters { get; set; }
        public DbSet<SinaiLetterDownloadDetail> SinaiLetterDownloadDetails { get; set; }
        public DbSet<SpiritualArticle> SpiritualArticles { get; set; }
        public DbSet<SpiritualArticleDownloadDetail> SpiritualArticleDownloadDetails { get; set; }
        public DbSet<StudyBible> StudyBibles { get; set; }
        public DbSet<StudyBibleDownloadDetail> StudyBibleDownloadDetails { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
