//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrayBook
    {
        public int ContentId { get; set; }
        public Nullable<int> BooKId { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string BookContent { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LibraryIndex LibraryIndex { get; set; }
    }
}
