//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryIndex
    {
        public LibraryIndex()
        {
            this.BooksRequests = new HashSet<BooksRequest>();
            this.LibrayBooks = new HashSet<LibrayBook>();
            this.LibrayDownloadDetails = new HashSet<LibrayDownloadDetail>();
        }
    
        public int BooKId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NoOfPage { get; set; }
        public string Language { get; set; }
        public Nullable<bool> ContentStatus { get; set; }
    
        public virtual ICollection<BooksRequest> BooksRequests { get; set; }
        public virtual ICollection<LibrayBook> LibrayBooks { get; set; }
        public virtual ICollection<LibrayDownloadDetail> LibrayDownloadDetails { get; set; }
    }
}
