//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedInDetail
    {
        public int LoggedInId { get; set; }
        public string LoggedInBy { get; set; }
        public Nullable<System.DateTime> LastLoggedInDateAndTime { get; set; }
        public Nullable<int> LoggedInCountPerDay { get; set; }
        public int totalNoOfUsersLoggedInPerDay { get; set; }
    }
}
