//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarianStudy
    {
        public int MarianStudyId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDateAndTime { get; set; }
        public int totalDownloadedCount { get; set; }
    }
}
