//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrayerRain
    {
        public int PrayerRainId { get; set; }
        public string RefPrayerRainId { get; set; }
        public string Title { get; set; }
        public string Verses { get; set; }
        public string Prayer { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateAndTime { get; set; }
        public Nullable<System.DateTime> EditEndDateAndTime { get; set; }
        public string PrayerRainFilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public string PrayerRainCreatedBy { get; set; }
        public string PrayerRainUploadedBy { get; set; }
        public int totalDownloadedCount { get; set; }
    }
}
