//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnifyelshaddai.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationMaster
    {
        public int RMID { get; set; }
        public Nullable<int> BWSID { get; set; }
        public string EmailId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Qualification { get; set; }
        public string ParticipantType { get; set; }
        public Nullable<bool> NeedOfAccommodation { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual BibleWorkShop BibleWorkShop { get; set; }
    }
}
